/simulation_bridge:
  ros__parameters:
    init_pos_x: '0.0'
    init_pos_y: '0.0'
    init_pos_yaw: '0.0'
    goals:
      goal0: {x_pos: 6.0, y_pos: 0.0, yaw: 0.0}
      goal1: {x_pos: 0.0, y_pos: 0.0, yaw: 0.0}