hunav_loader:
  ros__parameters:
    map: cafe
    publish_people: true
    agents:
      - agent1
    agent1:
      id: 1
      skin: 0
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: -4.990457
        y: -0.455264
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 7.126722
        y: -0.490281
        h: 1.250000