hunav_loader:
  ros__parameters:
    map: simple
    publish_people: true
    agents:
      - agent1
      - agent2
      - agent3
    agent1:
      id: 1
      skin: 0
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: -4.155396
        y: 4.803797
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 6.125517
        y: 5.700662
        h: 1.250000
      g1:
        x: 1.632029
        y: 9.051845
        h: 1.250000
    agent2:
      id: 2
      skin: 1
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: -3.321691
        y: 9.297482
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
      g0:
        x: 3.236912
        y: 3.543531
        h: 1.250000
    agent3:
      id: 3
      skin: 5
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: 8.943613
        y: 2.827306
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -7.342672
        y: 2.840789
        h: 1.250000
      g1:
        x: -8.869834
        y: 12.307944
        h: 1.250000
      g2:
        x: 10.744596
        y: 12.675598
        h: 1.250000
