hunav_loader:
  ros__parameters:
    map: cafe
    publish_people: true
    agents:
      - Agent1
      - Agent2
    Agent1:
      id: 1
      skin: 0
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: 14.475199
        y: -12.527378
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
        - g2
      g0:
        x: -9.691610
        y: -12.244225
        h: 1.250000
      g1:
        x: -10.338256
        y: -13.041624
        h: 1.250000
      g2:
        x: -11.231932
        y: 11.320541
        h: 1.250000
    Agent2:
      id: 2
      skin: 0
      behavior: 1
      group_id: -1
      max_vel: 1.5
      radius: 0.4
      init_pose:
        x: -11.312961
        y: 11.439453
        z: 1.250000
        h: 0.0
      goal_radius: 0.3
      cyclic_goals: true
      goals:
        - g0
        - g1
      g0:
        x: 12.784839
        y: 11.471436
        h: 1.250000
      g1:
        x: 3.745107
        y: 0.815639
        h: 1.250000